### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by F4310**
"I made an app that uses Wire-pod to control Vector through an Android smartphone. If you allow for disclosure, please approve the change. Kind regards, Fabio Silva

### CODE REVIEW

**Comment by TheGithubJoshua** [comment]
@F4310 can you share your app? I'm not the owner of this repo, just wanted to see it.

**Comment by F4310** [comment]
> @F4310 can you share your app? I'm not the owner of this repo, just wanted to see it.

https://play.google.com/store/apps/details?id=com.wireextent.vector_wire_extent

**Comment by kercre123** [comment]
I would prefer to keep the README as simple as possible

**Comment by TheGithubJoshua** [comment]
@F4310 can you please publish the source, I'm curious to see how it taps into wire-pod, so I could build an iOS version.

**Comment by F4310** [comment]
> @F4310 can you please publish the source, I'm curious to see how it taps into wire-pod, so I could build an iOS version.

See https://github.com/F4310/Vector-Wire-Pod-Extent

**Comment by TheGithubJoshua** [comment]
Thx for making that repo. I know you didn't create the API but the cloud intents don't work on my vector, everything else is fine though.

**Pull request closed without merging**
