### PR TITLE
Add Vosk STT engine to wire-pod and add dual language intent support (english/italian)

### PR DESCRIPTION
**Pull request by fforchino**
Hi, here's my changes to add another STT engine to chipper.
It's Vosk. I think its performances in English are in line with the previous STT supported by wire-pod, but using a rather small language model (around 40 Mb). It supports several languages, and my aim ultimately was localizing Vosk in languages other than English. I added Italian, and I had to split (only for vosk voice processor) the files dealing with intent recognition.
The work can be enhanced by taking intent text strings from json files instead of hardcoding them into the .go code.
I can do that in future, so that adding new languages it's even simpler.

Of course even if Vector understands Italian it always and only speaks English only, but when I get my OSKR ota image things may change... :)

The "chipper/customIntents.json" file should be added to .gitignore, but I left it out for now. You can ignore the changes there, just my own intents that interact with the vector sdk...

### CODE REVIEW

**Comment by kercre123** [comment]
Thanks! I have not heard of Vosk before, I am surprised by its speed and accuracy. I like your implementation, but may you add support for x86_64 and armv7 architectures in setup.sh? I can also do it if you want. Then I would feel fully comfortable merging into main

**Comment by fforchino** [comment]
Hi Wire, sorry about that, I totally forgot.
As far as this it is just downloading a different .so according to the
architecture around line 199, it's not a problem. But I'm not sure how to
test it because I haven't built wire-pod for anything but Raspberry Pi.
I'll do the changes to setup.sh and then resubmit the pull request.

Regards,
Filippo

**Comment by fforchino** [comment]
Done.

**Comment by fforchino** [comment]
But there is no x86 64 bit release of the libraries on github. Only 32
bit...


Il Sab 15 Ott 2022, 17:09 Wire ***@***.***> ha scritto:

**Comment by kercre123** [comment]
There is a little "Show all 13 assets" button under all of the assets which reveals the 64 bit release. I have implemented it and pushed it into main

**Pull request merged**
