### PR TITLE
Added Initial Setup in WS and changed a bit graphics

### PR DESCRIPTION
**Pull request by fforchino**
Hi, this goes in the direction of building a RPi image with a pre-installed VectorX and Wirepod.
I have changed the look of the WS pages using FontAwesome icons to implement a rudimental toolbar.
I have also added an "Initial Setup" menu that is able to patch source.sh and restart the Wirepod service to apply changes.
I may make some more changes in the future to tweak. This is not tested at 100%, feel free to delay the PR integration if you find some issues or you want changes, I'll try to cope.

I am building a component (https://github.com/fforchino/vectorx-wifi-setup) that puts the RPI in hotspot mode if wifi is not set, and allows user to configurre wifi. At the moment this is thought to work with an image that has a pre-installed and pre-configured version of wirepod and vectorx.

### CODE REVIEW

**Comment by Hamlet3000** [comment]
Hello,

thank you for the feedback. It sounds great and I'm glad to hear that there is more development going on here. If there are any conflicts, please just ignore my changes. Since I'm not a developer, I'm sure my code is not very clean ;-)

Unfortunately I have not managed to get VectorX running on my raspberry. I don't know the error message anymore, or do not know why it failed. I will wait for the WirePod & VectorX image and try again.

Until then I will practice some hmtl and css in my branch :-)

**Comment by fforchino** [comment]
Hmm, I didn't see that there was a pening pull request. Since we both touched the Web Server there will be conflicts for sure. I don't care too much about the layout, but the important for me is that the new initial setup menu is preserved. Then style it the way it looks better...

**Comment by kercre123** [comment]
Merging - I like what you have done with the UI. I do have some ideas which I can implement later. Implementing the features from wire-prod-pod into wire-pod is something I have been experimenting with, since at this point I would rather have one big codebase than two seperate ones. The differentiating factor in wire-prod-pod is that it uses the webserver for configuration and outputs to JSON rather than an env file, and the main thread is the config webserver rather than GRPC, so the webserver can be used to start/stop the wirepod voice processor without restarting the whole program. I like what you have

**Comment by Hamlet3000** [comment]
Hi,

fforchino build I think is cool too, I will try to implement the radio buttons as much as possible in settings.html and make the css a bit prettier and more responsive. I hope the green accents are ok? I'll try to implement it so that you can change the accent color with very little effort (maybe someday through the interface settings).

I won't touch functionalities anyway. I'm just trying to make the interface a bit prettier :-)

**Pull request merged**
