### PR TITLE
added a logo

### PR DESCRIPTION
**Pull request by xanathon**

### CODE REVIEW

**Comment by xanathon** [comment]
If you like it, I'll add it to the chipper web ui

**Comment by kercre123** [comment]
Thanks! I like the first one

**Comment by xanathon** [comment]
They are for different use scenarios, the second one may be better for smaller pixel sizes.

**Comment by kercre123** [comment]
I approve of adding it to the web UI. Will you be adding it to the UI as part of this PR?

**Comment by xanathon** [comment]
Yes, I can do that. I'll push the update as soon as I find time.

**Comment by kercre123** [comment]
Closing because it has been implemented in wire-prod-pod

**Pull request closed without merging**
