### PR TITLE
Vector Battery Status

### LINKED ISSUE #309: Feature request: Battery usage statistic
Hello, I use MQTT to log the battery consumption of my vecotor. Perhaps it would be possible to display this in the app under statistics? The layout could be based on the stimulation graph. It would be great if someone had the time and inclination to implement this. unfortunately I don't have the skills for it.

Screenshot 2024-04-17 172357

I already have prepared the graphical user interface for displaying the battery status under statistics. Someone would just have to implement the get_battery_status function. Unfortunately I don't have the go knowledge for thisv

### PR DESCRIPTION
**Pull request by AshMartian**
First off, thank you so much for this repository and keeping Vector alive 💚 

I saw a closed PR on battery status #310, and thought it would be a nice way to learn how Wire Pod works. So I obsessively tackled creating a nice UX for displaying battery stats. This could resolve #309

- On the home page, load the sdk info, if no bots are found, show nothing.
- New sdk-api endpoint for battery status `/api-sdk/get_battery`
- For each bot found, render a battery icon with a vector face that indicates the status.
  - Battery status is refreshed for each bot 3s after rendering
  - Face states for network loading/error, charging, roaming and needs charger.
  - Battery voltage determines the "percentage" shown, which is a log10 non-linear curve approximation (hence ~%)
  - Battery number level / percentage reported from Vector indicates color, 2-3 (100-50%) = green, 1 (50-20%) = yellow, 0 (>20%) = red
    - Battery percentage capped at 20% if level reported is 1
  - Batteries are in a flex box that should go full width and wrap. I only have 2 vectors to validate this visually. 
  - Battery charge time remaining rendered in lower left of battery
- Tooltip on battery hover shows the bot serial, estimated charge percentage, and raw voltage
- Clicking on a battery takes the browser straight to the bot settings
  - Bot settings page renders a single battery view for the bot in question
- Found some fetch issues when setting up my bots on BLE, tackled these and re-configured my bots with much higher success, might help with #284
- Checking for length of robots in connTimer, to resolve:
```
panic: runtime error: index out of range [1] with length 1

goroutine 601 [running]:
github.com/kercre123/wire-pod/chipper/pkg/wirepod/sdkapp.connTimer(0x1)
        /home/ash/wire-pod/chipper/pkg/wirepod/sdkapp/robot.go:149 +0x21c
created by github.com/kercre123/wire-pod/chipper/pkg/wirepod/sdkapp.newRobot in goroutine 28
        /home/ash/wire-pod/chipper/pkg/wirepod/sdkapp/robot.go:107 +0x4ec
```
- New `common.js` file for loading sdkInfo and getting battery status, since these are needed on home and settings

https://github.com/user-attachments/assets/f41bfcd4-1cff-491e-aeda-da81e6fcc94f

Full Charged
image
Roaming
image
Needs Charging
image
Charging with ETA
image
Charging with Tooltip
image
Loading
image
Network error
image

## Issues
- Thinking the % approximation should be done and returned from the api endpoint, to serve 3rd party usages as well.
- Vector only sends new voltages while charging or just leaving the charger. 
  - Unsure if this is an sdk limitation or firmware, can't find any documentation but seems out of scope for this PR

### CODE REVIEW

**Comment by Zomboy4313** [comment]
One small thing I would change is instead of using a question mark, maybe use a ~ symbol since it means approximately

**Comment by AshMartian** [comment]
Good idea @Zomboy4313, implemented

**Comment by kercre123** [comment]
This implementation is so cute! A battery indicator has been requested before, but I've been hesitant because of the same issues you ran into. Specifically: new voltages being sent not very often. I believe this to be a firmware limitation. It is also hard to be precise with the battery since there isn't a "fuel gauge" like a smartphone would have. Your curve idea seems accurate enough, though.

Just one nitpick: when no bots are authenticated, there is a bit of empty space between the header and content in the main page. If that is fixed, I will merge this.

I like this idea a lot. I wonder if we could replicate the "Vector is doing <action>..." indicator that was in the Vector mobile app. Vector has an event stream which provides things like that. In my testing though, I couldn't figure out how to correspond a "RobotState.Status" with one of the proto-defined statuses.

**Comment by AshMartian** [comment]
Awesome ideas @kercre123! Thanks for removing the botStats element on no bots!

I also pondered more animations and expanding on the robot status, included is a blank face which we could make more gif animations for various status states! (the home charging png I made in photoshop) To be clear, Vector's firmware was not open sourced, correct? We can't push firmware updates or on board logic with the vector-cloud server?

I was also thinking that this makes the "Bot Settings" page obsolete, since it's much faster to click into the bots from the homepage, but felt removing that was outside scope and didn't want to interrupt any workflows utilizing that functionality.

**Comment by kercre123** [comment]
Right, we can't change the robot firmware. Some parts were open-sourced, but we don't have enough of the code to fully build our own firmware. Even if we could build it, we'd have no way to sign it and run it on a production bot.

The animations were fully open-sourced. The more complex ones have [sprite sequences](https://github.com/digital-dream-labs/vector-animations-build/tree/main/assets/sprites/spriteSequences) which could be turned into GIFs. For regular animation files, a dev robot could be used to capture it.

The Bot Settings page is probably unneeded now.. I think I'll leave it in for now since all of the YouTube wire-pod setup tutorials still refer to it and such.

**Comment by AshMartian** [comment]
Oooo awesome tip on those sprite sequences! I'll keep them in mind and maybe raise a PR for an animated home/charging GIF

**Pull request merged**
