### PR TITLE
battery status in statistics

### PR DESCRIPTION
**Pull request by Hamlet3000**
With regard to issue [#309](https://github.com/kercre123/wire-pod/issues/309), I have prepared the graphical user interface for displaying the battery status under statistics. Someone would just have to implement the get_battery_status function. Unfortunately I don't have the go knowledge for this.

Screenshot 2024-04-17 172136

### CODE REVIEW

**Comment by bliteknight** [comment]
The unfortunate issue with the SDK is the battery level will always be a constant value when read e.g. 4.9v but the status will either be good, charging, or needs to charge....so this graph will always have a horizontal line that changes from read to read...it wont ever slope down or up :(

**Comment by kercre123** [comment]
When he is taken off the charger, the voltage value just stays the same in my experience, even after 10 minutes or so. I don't know if this is an issue with the vector-go-sdk or if it is expected.

**Comment by Hamlet3000** [comment]
I already have a go lang script that reliably gives me the battery voltage and docking status from vector, I just don't know how best to implement it in wire-pod... I can post it here later. It would be great if you could take a look at it and help me with it.

**Comment by Hamlet3000** [comment]
As promised, here is the go lang code that supplies the voltage every 10 seconds:
https://github.com/Hamlet3000/Vector-mqtt.go/blob/main/mqtt.go

I am currently using the script as a service on wire-pod to send the values to my smarthome via MQTT (see also issue [#312](https://github.com/kercre123/wire-pod/issues/312)). It would be great if someone could help me with the implementation in wire-pod and maybe realize both issues. Please feel free to use my code.

**Comment by kercre123** [comment]
MQTT support is something i'd like to add to WirePod in the future, but I think i'd want to send more than just docked status+voltage. Is there any reason you'd like this to be a part of wire-pod rather than stay as a seperate process?

**Comment by Hamlet3000** [comment]
Docking status and battery are the things that the SDK already supports, so I think it should be relatively easy to integrate. It would be a great advantage for all users who don't want to or can't program to simply enter the IP and port of their MQTT broker via the interface and wire-pod does the rest.

I can of course live with my current solution, but it is customized for me with additional scripts and setting up a service.

**Pull request closed without merging**
