### PR TITLE
style: revamp navigation items with modern interactions and interactive hover effects and improve navigation experience

### PR DESCRIPTION
**Pull request by PeskyVector**
Hi! (This is my first pull request so bare with me here)

## Why
The navigation experience was not as smooth and pretty as it could be.

## What I did

- I updated the icon hover effects with a white border, and a smooth hover effect with a upwards animations
- I utilized the icon selected state so when selected, the border has a foreground color
- Added a slight background tint to indicate what items are selected
- Added ease in out animations to the switching of item states
- Added custom css for small devices (adjusted hover effect)
-Modified navigation icon layout to be a grid on mobile, a line on desktop (when enough space, otherwise it's a wrappable grid)
-Added PWA meta tags for iOS devices on index.html , hiding the search bar, and theming the status bar correctly

-Removed horizontal scroll on mobile for a better experience

## Testing Done

- Tested selected item state on reload
- Tested functionality on main navigation page 
- Tested selected item state on navigation links (eg bot settings)
- Testing smooth handling of changing accent colour
-Tested modified navigation layout on different devices
-Tested reactive scaling without reloading
-Tested modified navigation layout on other pages
-Tested mobile layout on add to Home Screen on iOS and iPad. 

_To do:_

- [ ] Handle the PWA website links for bot settings and other pages when added to home screen. 
- [ ] Correct meta tags on other files

**Navigation Hover effect before**:
before

**Navigation Hover effect after**
after

**Add to home screen before**
image

**Add to homescreen after**
image

### CODE REVIEW

**Comment by PeskyVector** [comment]
This actually breaks it on mobile. Don't merge please.

**Comment by PeskyVector** [comment]
Wirepod uses different pages for `bot settings, server settings,` which causes the PWA to open in a in app browser. I can either modify all redirection logic undo PWA.

**Comment by PeskyVector** [comment]
I removed the PWA experience on mobile for now. Will create another pull request when ready.

**Comment by PeskyVector** [comment]
I think it's ready to be merged.

**Comment by kercre123** [comment]
thx!

**Pull request merged**
